name: avatar
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults

dependencies:
  - python=3.10

  # Core
  - numpy
  - tqdm
  - pillow
  - networkx

  # PyTorch
  - pytorch
  - torchvision

  # Optional but commonly needed
  - pip

  # Pip packages
  - pip:
      - torch-geometric
      - open_clip_torch
      - pycocotools